# Usar a imagem oficial do OpenJDK 20
FROM openjdk:17

# Criar um diretório para o app
WORKDIR /app

# Copiar o arquivo JAR para o contêiner
COPY target/pagamentos-1.0-SNAPSHOT.jar pagamentos.jar

# Expor a porta do RMI (1099)
EXPOSE 1099

# Comando para rodar o servidor
ENTRYPOINT ["java", "-jar", "pagamentos.jar"]